AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Racelens Serverless

Parameters:
  Stage:
    Type: String
    Default: dev
  RekognitionCollectionName:
    Type: String
    Default: racelens_dev
  BucketName:
    Type: String
    Default: racelens-images-dev
  DynamoDBTableName:
    Type: String
    Default: racelens_dev
  DomainName:
    Type: String
    Default: racelens.ml
  HostedZoneId:
    Type: String

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64
    CodeUri: lambda/
    Environment:
      Variables:
        COLLECTION_NAME: !Ref RekognitionCollectionName
        DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName

Resources:
  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors: "'*'"
      BinaryMediaTypes: ["*~1*"]
      Domain:
        DomainName: !Sub "api-dev.${DomainName}"
        CertificateArn: !Ref DomainCertificate
        Route53:
          HostedZoneId: !Ref HostedZoneId

  IndexFaces:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.index_faces
      MemorySize: 128
      Policies:
        - AmazonS3FullAccess
        - AmazonRekognitionFullAccess
        - AmazonDynamoDBFullAccess
      Events:
        IndexFacesEvent:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:*
  FindFaces:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.find_faces
      MemorySize: 512 # TODO: #3 Check if it works with 128
      Policies:
        - AmazonS3FullAccess
        - AmazonRekognitionFullAccess
        - AmazonDynamoDBFullAccess
      Timeout: 5
      Events:
        Find:
          Type: Api
          Properties:
            RestApiId: !Ref RestApiGateway
            Path: /{event_name}/find
            Method: post

  RekognitionCollection:
    Type: AWS::Rekognition::Collection
    Properties:
      CollectionId: !Ref RekognitionCollectionName

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
  ImagesDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Sub "images-dev.${DomainName}"
        PriceClass: PriceClass_100
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          DefaultTTL: 86400
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainCertificate
          SslSupportMethod: sni-only
        Origins:
          - DomainName: !Sub "${BucketName}.s3.amazonaws.com"
            Id: "S3Origin"
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - ""
                - - "origin-access-identity/cloudfront/"
                  - !Ref ImagesOAI
  ImagesOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Racelens images
  ImagesDistributionRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub "images-dev.${DomainName}"
          Type: A
          AliasTarget:
            DNSName: !GetAtt ImagesDistribution.DomainName
            HostedZoneId: !Sub "Z2FDTNDATAQYW2"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: !Ref DynamoDBTableName
      Tags:
        - Key: key
          Value: value

  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub "*.${DomainName}"
      DomainValidationOptions:
        - DomainName: !Sub "*.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS
