AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Racelens Serverless

Parameters:
  RekognitionCollectionName:
    Type: String
    Default: racelens-dev
  BucketName:
    Type: String
    Default: racelens-images-dev

Globals:
  Function:
    Timeout: 3
    Runtime: python3.9
    Architectures:
      - x86_64
    CodeUri: lambda/
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'*'"
    BinaryMediaTypes: [ '*~1*' ]

Resources:
  RekognitionCollection:
    Type: AWS::Rekognition::Collection
    Properties:
      CollectionId: !Ref RekognitionCollectionName
  
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
  